using NPKOptimizer.Components.Builders;
using NPKOptimizer.Domain.Elements;
using NPKOptimizer.Enums;

// ReSharper disable UnusedMember.Global

namespace NPKOptimizer.Common;

public static class Atom
{
    public static readonly Element H = new AtomBuilder()
        .Name("Hydrogen")
        .Symbol("H")
        .AtomicNumber(1)
        .AtomicMass(1.008)
        .OxidationStates(1, -1)
        .Electronegativity(2.20)
        .IonizationEnergy(1312.0)
        .ElectronAffinity(72.8)
        .AtomicRadius(53)
        .MeltingPoint(-259.14)
        .BoilingPoint(-252.87)
        .Type(ElementType.NonMetal)
        .Build();
    public static readonly Element He = new AtomBuilder()
        .Name("Helium")
        .Symbol("He")
        .AtomicNumber(2)
        .AtomicMass(4.002602)
        .IonizationEnergy(2372.3)
        .ElectronAffinity(0)
        .AtomicRadius(31)
        .BoilingPoint(-268.93)
        .Type(ElementType.NonMetal)
        .Build();
    public static readonly Element Li = new AtomBuilder()
        .Name("Lithium")
        .Symbol("Li")
        .AtomicNumber(3)
        .AtomicMass(6.94)
        .OxidationStates(1)
        .Electronegativity(0.98)
        .IonizationEnergy(520.2)
        .ElectronAffinity(59.6)
        .AtomicRadius(152)
        .MeltingPoint(180.54)
        .BoilingPoint(1342)
        .Type(ElementType.Metal)
        .Build();
    public static readonly Element Be = new AtomBuilder()
        .Name("Beryllium")
        .Symbol("Be")
        .AtomicNumber(4)
        .AtomicMass(9.0122)
        .OxidationStates(2)
        .Electronegativity(1.57)
        .IonizationEnergy(899.5)
        .AtomicRadius(112)
        .MeltingPoint(1287)
        .BoilingPoint(2469)
        .Type(ElementType.Metal)
        .Build();
    public static readonly Element B = new AtomBuilder()
        .Name("Boron")
        .Symbol("B")
        .AtomicNumber(5)
        .AtomicMass(10.81)
        .OxidationStates(3)
        .Electronegativity(2.04)
        .IonizationEnergy(800.6)
        .ElectronAffinity(26.7)
        .AtomicRadius(90)
        .MeltingPoint(2075)
        .BoilingPoint(4000)
        .Type(ElementType.Metalloid)
        .Build();
    public static readonly Element C = new AtomBuilder()
        .Name("Carbon")
        .Symbol("C")
        .AtomicNumber(6)
        .AtomicMass(12.011)
        .OxidationStates(-4, 2, 4)
        .Electronegativity(2.55)
        .IonizationEnergy(1086.5)
        .ElectronAffinity(153.9)
        .AtomicRadius(70)
        .MeltingPoint(3550)
        .BoilingPoint(4827)
        .Type(ElementType.NonMetal)
        .Build();
    public static readonly Element N = new AtomBuilder()
        .Name("Nitrogen")
        .Symbol("N")
        .AtomicNumber(7)
        .AtomicMass(14.007)
        .OxidationStates(-3, 3, 5)
        .Electronegativity(3.04)
        .IonizationEnergy(1402.3)
        .ElectronAffinity(-6.8)
        .AtomicRadius(65)
        .MeltingPoint(-210.0)
        .BoilingPoint(-195.8)
        .Type(ElementType.NonMetal)
        .Build();
    public static readonly Element O = new AtomBuilder()
        .Name("Oxygen")
        .Symbol("O")
        .AtomicNumber(8)
        .AtomicMass(15.999)
        .OxidationStates(-2)
        .Electronegativity(3.44)
        .IonizationEnergy(1313.9)
        .ElectronAffinity(140.976)
        .AtomicRadius(60)
        .MeltingPoint(-218.79)
        .BoilingPoint(-182.96)
        .Type(ElementType.NonMetal)
        .Build();
    public static readonly Element F = new AtomBuilder()
        .Name("Fluorine")
        .Symbol("F")
        .AtomicNumber(9)
        .AtomicMass(18.998)
        .OxidationStates(-1)
        .Electronegativity(3.98)
        .IonizationEnergy(1681.0)
        .ElectronAffinity(328.2)
        .AtomicRadius(50)
        .MeltingPoint(-219.67)
        .BoilingPoint(-188.11)
        .Type(ElementType.NonMetal)
        .Build();
    public static readonly Element Ne = new AtomBuilder()
        .Name("Neon")
        .Symbol("Ne")
        .AtomicNumber(10)
        .AtomicMass(20.1797)
        .IonizationEnergy(2080.7)
        .AtomicRadius(38)
        .MeltingPoint(-248.59)
        .BoilingPoint(-246.08)
        .Type(ElementType.NonMetal)
        .Build();
    public static readonly Element Na = new AtomBuilder()
        .Name("Sodium")
        .Symbol("Na")
        .AtomicNumber(11)
        .AtomicMass(22.98976928)
        .OxidationStates(1)
        .Electronegativity(0.93)
        .IonizationEnergy(495.8)
        .ElectronAffinity(52.8)
        .AtomicRadius(180)
        .MeltingPoint(97.72)
        .BoilingPoint(883)
        .Type(ElementType.Metal)
        .Build();
    public static readonly Element Mg = new AtomBuilder()
        .Name("Magnesium")
        .Symbol("Mg")
        .AtomicNumber(12)
        .AtomicMass(24.305)
        .OxidationStates(2)
        .Electronegativity(1.31)
        .IonizationEnergy(737.7)
        .AtomicRadius(145)
        .MeltingPoint(650)
        .BoilingPoint(1090)
        .Type(ElementType.Metal)
        .Build();
    public static readonly Element Al = new AtomBuilder()
        .Name("Aluminum")
        .Symbol("Al")
        .AtomicNumber(13)
        .AtomicMass(26.9815386)
        .OxidationStates(3)
        .Electronegativity(1.61)
        .IonizationEnergy(577.5)
        .ElectronAffinity(42.5)
        .AtomicRadius(118)
        .MeltingPoint(660.32)
        .BoilingPoint(2519)
        .Type(ElementType.Metal)
        .Build();
    public static readonly Element Si = new AtomBuilder()
        .Name("Silicon")
        .Symbol("Si")
        .AtomicNumber(14)
        .AtomicMass(28.085)
        .OxidationStates(-4, 4)
        .Electronegativity(1.90)
        .IonizationEnergy(786.5)
        .ElectronAffinity(133.6)
        .AtomicRadius(111)
        .MeltingPoint(1414)
        .BoilingPoint(2900)
        .Type(ElementType.Metalloid)
        .Build();
    public static readonly Element P = new AtomBuilder()
        .Name("Phosphorus")
        .Symbol("P")
        .AtomicNumber(15)
        .AtomicMass(30.973762)
        .OxidationStates(-3, 3, 5)
        .Electronegativity(2.19)
        .IonizationEnergy(1011.8)
        .ElectronAffinity(72)
        .AtomicRadius(98)
        .MeltingPoint(44.2)
        .BoilingPoint(280.5)
        .Type(ElementType.NonMetal)
        .Build();
    public static readonly Element S = new AtomBuilder()
        .Name("Sulfur")
        .Symbol("S")
        .AtomicNumber(16)
        .AtomicMass(32.06)
        .OxidationStates(-2, 2, 4, 6)
        .Electronegativity(2.58)
        .IonizationEnergy(999.6)
        .ElectronAffinity(200)
        .AtomicRadius(88)
        .MeltingPoint(115.21)
        .BoilingPoint(444.6)
        .Type(ElementType.NonMetal)
        .Build();
    public static readonly Element Cl = new AtomBuilder()
        .Name("Chlorine")
        .Symbol("Cl")
        .AtomicNumber(17)
        .AtomicMass(35.45)
        .OxidationStates(-1, 1, 3, 5, 7)
        .Electronegativity(3.16)
        .IonizationEnergy(1251.2)
        .ElectronAffinity(348.575)
        .AtomicRadius(100)
        .MeltingPoint(-101.5)
        .BoilingPoint(-34.04)
        .Type(ElementType.NonMetal)
        .Build();
    public static readonly Element Ar = new AtomBuilder()
        .Name("Argon")
        .Symbol("Ar")
        .AtomicNumber(18)
        .AtomicMass(39.948)
        .IonizationEnergy(1520.6)
        .AtomicRadius(71)
        .MeltingPoint(-189.34)
        .BoilingPoint(-185.848)
        .Type(ElementType.NonMetal)
        .Build();
    public static readonly Element K = new AtomBuilder()
        .Name("Potassium")
        .Symbol("K")
        .AtomicNumber(19)
        .AtomicMass(39.0983)
        .OxidationStates(1)
        .Electronegativity(0.82)
        .IonizationEnergy(418.8)
        .ElectronAffinity(48.4)
        .AtomicRadius(243)
        .MeltingPoint(63.5)
        .BoilingPoint(759)
        .Type(ElementType.Metal)
        .Build();

    public static readonly Element Ca = new AtomBuilder()
        .Name("Calcium")
        .Symbol("Ca")
        .AtomicNumber(20)
        .AtomicMass(40.078)
        .OxidationStates(2)
        .Electronegativity(1.00)
        .IonizationEnergy(589.8)
        .ElectronAffinity(2.37)
        .AtomicRadius(194)
        .MeltingPoint(842)
        .BoilingPoint(1484)
        .Type(ElementType.Metal)
        .Build();

    public static readonly Element Sc = new AtomBuilder()
        .Name("Scandium")
        .Symbol("Sc")
        .AtomicNumber(21)
        .AtomicMass(44.955908)
        .OxidationStates(3)
        .Electronegativity(1.36)
        .IonizationEnergy(633.1)
        .ElectronAffinity(18.2)
        .AtomicRadius(184)
        .MeltingPoint(1541)
        .BoilingPoint(2836)
        .Type(ElementType.Metal)
        .Build();

    public static readonly Element Ti = new AtomBuilder()
        .Name("Titanium")
        .Symbol("Ti")
        .AtomicNumber(22)
        .AtomicMass(47.867)
        .OxidationStates(2, 3, 4)
        .Electronegativity(1.54)
        .IonizationEnergy(658.8)
        .ElectronAffinity(7.6)
        .AtomicRadius(176)
        .MeltingPoint(1668)
        .BoilingPoint(3287)
        .Type(ElementType.Metal)
        .Build();

    public static readonly Element V = new AtomBuilder()
        .Name("Vanadium")
        .Symbol("V")
        .AtomicNumber(23)
        .AtomicMass(50.9415)
        .OxidationStates(2, 3, 4, 5)
        .Electronegativity(1.63)
        .IonizationEnergy(650.9)
        .ElectronAffinity(50.6)
        .AtomicRadius(171)
        .MeltingPoint(1910)
        .BoilingPoint(3407)
        .Type(ElementType.Metal)
        .Build();

    public static readonly Element Cr = new AtomBuilder()
        .Name("Chromium")
        .Symbol("Cr")
        .AtomicNumber(24)
        .AtomicMass(51.9961)
        .OxidationStates(2, 3, 6)
        .Electronegativity(1.66)
        .IonizationEnergy(652.9)
        .ElectronAffinity(64.3)
        .AtomicRadius(166)
        .MeltingPoint(1907)
        .BoilingPoint(2671)
        .Type(ElementType.Metal)
        .Build();

    public static readonly Element Mn = new AtomBuilder()
        .Name("Manganese")
        .Symbol("Mn")
        .AtomicNumber(25)
        .AtomicMass(54.938045)
        .OxidationStates(2, 3, 4, 6, 7)
        .Electronegativity(1.55)
        .IonizationEnergy(717.3)
        .ElectronAffinity(0)  // Electron affinity of manganese is effectively zero
        .AtomicRadius(161)
        .MeltingPoint(1246)
        .BoilingPoint(2061)
        .Type(ElementType.Metal)
        .Build();

    public static  readonly Element Fe = new AtomBuilder()
        .Name("Iron")
        .Symbol("Fe")
        .AtomicNumber(26)
        .AtomicMass(55.845)
        .OxidationStates(2, 3)
        .Electronegativity(1.83)
        .IonizationEnergy(762.5)
        .ElectronAffinity(15.7)
        .AtomicRadius(156)
        .MeltingPoint(1538)
        .BoilingPoint(2862)
        .Type(ElementType.Metal)
        .Build();
    public static readonly Element Co = new AtomBuilder()
        .Name("Cobalt")
        .Symbol("Co")
        .AtomicNumber(27)
        .AtomicMass(58.933195)
        .OxidationStates(2, 3)
        .Electronegativity(1.88)
        .IonizationEnergy(760.4)
        .ElectronAffinity(63.7)
        .AtomicRadius(152)
        .MeltingPoint(1495)
        .BoilingPoint(2927)
        .Type(ElementType.Metal)
        .Build();

    public static readonly Element Ni = new AtomBuilder()
        .Name("Nickel")
        .Symbol("Ni")
        .AtomicNumber(28)
        .AtomicMass(58.6934)
        .OxidationStates(2, 3)
        .Electronegativity(1.91)
        .IonizationEnergy(737.1)
        .ElectronAffinity(111.65)
        .AtomicRadius(149)
        .MeltingPoint(1455)
        .BoilingPoint(2913)
        .Type(ElementType.Metal)
        .Build();

    public static readonly Element Cu = new AtomBuilder()
        .Name("Copper")
        .Symbol("Cu")
        .AtomicNumber(29)
        .AtomicMass(63.546)
        .OxidationStates(1, 2)
        .Electronegativity(1.90)
        .IonizationEnergy(745.5)
        .ElectronAffinity(118.4)
        .AtomicRadius(145)
        .MeltingPoint(1085)
        .BoilingPoint(2562)
        .Type(ElementType.Metal)
        .Build();

    public static readonly Element Zn = new AtomBuilder()
        .Name("Zinc")
        .Symbol("Zn")
        .AtomicNumber(30)
        .AtomicMass(65.38)
        .OxidationStates(2)
        .Electronegativity(1.65)
        .IonizationEnergy(906.4)
        .ElectronAffinity(0)
        .AtomicRadius(142)
        .MeltingPoint(419.5)
        .BoilingPoint(907)
        .Type(ElementType.Metal)
        .Build();

    public static readonly Element Ga = new AtomBuilder()
        .Name("Gallium")
        .Symbol("Ga")
        .AtomicNumber(31)
        .AtomicMass(69.723)
        .OxidationStates(3)
        .Electronegativity(1.81)
        .IonizationEnergy(578.8)
        .ElectronAffinity(41)
        .AtomicRadius(136)
        .MeltingPoint(29.76)
        .BoilingPoint(2204)
        .Type(ElementType.Metal)
        .Build();

    public static readonly Element Ge = new AtomBuilder()
        .Name("Germanium")
        .Symbol("Ge")
        .AtomicNumber(32)
        .AtomicMass(72.630)
        .OxidationStates(-4, 2, 4)
        .Electronegativity(2.01)
        .IonizationEnergy(762)
        .ElectronAffinity(119)
        .AtomicRadius(125)
        .MeltingPoint(938.3)
        .BoilingPoint(2820)
        .Type(ElementType.Metalloid)
        .Build();

    public static readonly Element As = new AtomBuilder()
        .Name("Arsenic")
        .Symbol("As")
        .AtomicNumber(33)
        .AtomicMass(74.921595)
        .OxidationStates(-3, 3, 5)
        .Electronegativity(2.18)
        .IonizationEnergy(947)
        .ElectronAffinity(78)
        .AtomicRadius(114)
        .MeltingPoint(817) // Sublimates
        .BoilingPoint(613)
        .Type(ElementType.Metalloid)
        .Build();

    public static readonly Element Se = new AtomBuilder()
        .Name("Selenium")
        .Symbol("Se")
        .AtomicNumber(34)
        .AtomicMass(78.971)
        .OxidationStates(-2, 4, 6)
        .Electronegativity(2.55)
        .IonizationEnergy(941)
        .ElectronAffinity(195)
        .AtomicRadius(103)
        .MeltingPoint(221)
        .BoilingPoint(685)
        .Type(ElementType.NonMetal)
        .Build();

    public static readonly Element Br = new AtomBuilder()
        .Name("Bromine")
        .Symbol("Br")
        .AtomicNumber(35)
        .AtomicMass(79.904)
        .OxidationStates(-1, 1, 3, 5)
        .Electronegativity(2.96)
        .IonizationEnergy(1139.9)
        .ElectronAffinity(324.6)
        .AtomicRadius(94)
        .MeltingPoint(-7.2)
        .BoilingPoint(58.8)
        .Type(ElementType.NonMetal)
        .Build();
    public static readonly Element Kr = new AtomBuilder()
        .Name("Krypton")
        .Symbol("Kr")
        .AtomicNumber(36)
        .AtomicMass(83.798)
        .IonizationEnergy(1350.8)
        .ElectronAffinity(0)
        .AtomicRadius(88)
        .MeltingPoint(-157.36)
        .BoilingPoint(-153.22)
        .Type(ElementType.NobleGas)
        .Build();

    public static readonly Element Rb = new AtomBuilder()
        .Name("Rubidium")
        .Symbol("Rb")
        .AtomicNumber(37)
        .AtomicMass(85.4678)
        .OxidationStates(1)
        .Electronegativity(0.82)
        .IonizationEnergy(403.0)
        .ElectronAffinity(46.9)
        .AtomicRadius(248)
        .MeltingPoint(39.31)
        .BoilingPoint(688)
        .Type(ElementType.AlkaliMetal)
        .Build();

    public static readonly Element Sr = new AtomBuilder()
        .Name("Strontium")
        .Symbol("Sr")
        .AtomicNumber(38)
        .AtomicMass(87.62)
        .OxidationStates(2)
        .Electronegativity(0.95)
        .IonizationEnergy(549.5)
        .ElectronAffinity(5.03)
        .AtomicRadius(215)
        .MeltingPoint(777)
        .BoilingPoint(1382)
        .Type(ElementType.AlkalineEarthMetal)
        .Build();

    public static readonly Element Y = new AtomBuilder()
        .Name("Yttrium")
        .Symbol("Y")
        .AtomicNumber(39)
        .AtomicMass(88.90584)
        .OxidationStates(3)
        .Electronegativity(1.22)
        .IonizationEnergy(600)
        .ElectronAffinity(29.6)
        .AtomicRadius(180)
        .MeltingPoint(1526)
        .BoilingPoint(3345)
        .Type(ElementType.TransitionMetal)
        .Build();

    public static readonly Element Zr = new AtomBuilder()
        .Name("Zirconium")
        .Symbol("Zr")
        .AtomicNumber(40)
        .AtomicMass(91.224)
        .OxidationStates(4)
        .Electronegativity(1.33)
        .IonizationEnergy(640.1)
        .ElectronAffinity(41.1)
        .AtomicRadius(155)
        .MeltingPoint(1855)
        .BoilingPoint(4409)
        .Type(ElementType.TransitionMetal)
        .Build();

    public static readonly Element Nb = new AtomBuilder()
        .Name("Niobium")
        .Symbol("Nb")
        .AtomicNumber(41)
        .AtomicMass(92.90637)
        .OxidationStates(3, 5)
        .Electronegativity(1.6)
        .IonizationEnergy(652.1)
        .ElectronAffinity(88.5)
        .AtomicRadius(145)
        .MeltingPoint(2477)
        .BoilingPoint(4744)
        .Type(ElementType.TransitionMetal)
        .Build();

    public static readonly Element Mo = new AtomBuilder()
        .Name("Molybdenum")
        .Symbol("Mo")
        .AtomicNumber(42)
        .AtomicMass(95.95)
        .OxidationStates(2, 3, 4, 5, 6)
        .Electronegativity(2.16)
        .IonizationEnergy(684.3)
        .ElectronAffinity(72.1)
        .AtomicRadius(145)
        .MeltingPoint(2623)
        .BoilingPoint(4639)
        .Type(ElementType.TransitionMetal)
        .Build();

    public static readonly Element Tc = new AtomBuilder()
        .Name("Technetium")
        .Symbol("Tc")
        .AtomicNumber(43)
        .AtomicMass(98) // Radioactive, most stable isotope
        .OxidationStates(4, 7)
        .Electronegativity(1.9)
        .IonizationEnergy(702)
        .ElectronAffinity(53)
        .AtomicRadius(156)
        .MeltingPoint(2157)
        .BoilingPoint(4265)
        .Type(ElementType.TransitionMetal)
        .Build();

    public static readonly Element Ru = new AtomBuilder()
        .Name("Ruthenium")
        .Symbol("Ru")
        .AtomicNumber(44)
        .AtomicMass(101.07)
        .OxidationStates(2, 3, 4, 6, 8)
        .Electronegativity(2.2)
        .IonizationEnergy(710.2)
        .ElectronAffinity(101.3)
        .AtomicRadius(126)
        .MeltingPoint(2334)
        .BoilingPoint(4150)
        .Type(ElementType.TransitionMetal)
        .Build();

    public static readonly Element Rh = new AtomBuilder()
        .Name("Rhodium")
        .Symbol("Rh")
        .AtomicNumber(45)
        .AtomicMass(102.90550)
        .OxidationStates(2, 3, 4)
        .Electronegativity(2.28)
        .IonizationEnergy(719.7)
        .ElectronAffinity(110.9)
        .AtomicRadius(135)
        .MeltingPoint(1964)
        .BoilingPoint(3695)
        .Type(ElementType.TransitionMetal)
        .Build();

    public static readonly Element Pd = new AtomBuilder()
        .Name("Palladium")
        .Symbol("Pd")
        .AtomicNumber(46)
        .AtomicMass(106.42)
        .OxidationStates(0, 2, 4)
        .Electronegativity(2.20)
        .IonizationEnergy(804.4)
        .ElectronAffinity(54.24)
        .AtomicRadius(131)
        .MeltingPoint(1554.9)
        .BoilingPoint(2963)
        .Type(ElementType.TransitionMetal)
        .Build();

    public static readonly Element Ag = new AtomBuilder()
        .Name("Silver")
        .Symbol("Ag")
        .AtomicNumber(47)
        .AtomicMass(107.8682)
        .OxidationStates(1, 2)
        .Electronegativity(1.93)
        .IonizationEnergy(731.0)
        .ElectronAffinity(125.6)
        .AtomicRadius(153)
        .MeltingPoint(961.78)
        .BoilingPoint(2162)
        .Type(ElementType.TransitionMetal)
        .Build();

    public static readonly Element Cd = new AtomBuilder()
        .Name("Cadmium")
        .Symbol("Cd")
        .AtomicNumber(48)
        .AtomicMass(112.414)
        .OxidationStates(2)
        .Electronegativity(1.69)
        .IonizationEnergy(867.8)
        .ElectronAffinity(0)
        .AtomicRadius(148)
        .MeltingPoint(321.07)
        .BoilingPoint(767)
        .Type(ElementType.TransitionMetal)
        .Build();

    public static readonly Element In = new AtomBuilder()
        .Name("Indium")
        .Symbol("In")
        .AtomicNumber(49)
        .AtomicMass(114.818)
        .OxidationStates(3)
        .Electronegativity(1.78)
        .IonizationEnergy(558.3)
        .ElectronAffinity(28.9)
        .AtomicRadius(144)
        .MeltingPoint(156.60)
        .BoilingPoint(2072)
        .Type(ElementType.PostTransitionMetal)
        .Build();

    public static readonly Element Sn = new AtomBuilder()
        .Name("Tin")
        .Symbol("Sn")
        .AtomicNumber(50)
        .AtomicMass(118.710)
        .OxidationStates(-4, 2, 4)
        .Electronegativity(1.96)
        .IonizationEnergy(708.6)
        .ElectronAffinity(107.3)
        .AtomicRadius(141)
        .MeltingPoint(231.93)
        .BoilingPoint(2602)
        .Type(ElementType.PostTransitionMetal)
        .Build();

    public static readonly Element Sb = new AtomBuilder()
        .Name("Antimony")
        .Symbol("Sb")
        .AtomicNumber(51)
        .AtomicMass(121.760)
        .OxidationStates(-3, 3, 5)
        .Electronegativity(2.05)
        .IonizationEnergy(834)
        .ElectronAffinity(103.2)
        .AtomicRadius(138)
        .MeltingPoint(630.63)
        .BoilingPoint(1587)
        .Type(ElementType.Metalloid)
        .Build();

    public static readonly Element Te = new AtomBuilder()
        .Name("Tellurium")
        .Symbol("Te")
        .AtomicNumber(52)
        .AtomicMass(127.60)
        .OxidationStates(-2, 4, 6)
        .Electronegativity(2.1)
        .IonizationEnergy(869.3)
        .ElectronAffinity(190.2)
        .AtomicRadius(135)
        .MeltingPoint(449.51)
        .BoilingPoint(988)
        .Type(ElementType.Metalloid)
        .Build();

    public static readonly Element I = new AtomBuilder()
        .Name("Iodine")
        .Symbol("I")
        .AtomicNumber(53)
        .AtomicMass(126.90447)
        .OxidationStates(-1, 1, 5, 7)
        .Electronegativity(2.66)
        .IonizationEnergy(1008.4)
        .ElectronAffinity(295.2)
        .AtomicRadius(133)
        .MeltingPoint(113.7)
        .BoilingPoint(184.3)
        .Type(ElementType.Halogen)
        .Build();

    public static readonly Element Xe = new AtomBuilder()
        .Name("Xenon")
        .Symbol("Xe")
        .AtomicNumber(54)
        .AtomicMass(131.293)
        .IonizationEnergy(1170.4)
        .ElectronAffinity(0)
        .AtomicRadius(130)
        .MeltingPoint(-111.8)
        .BoilingPoint(-108)
        .Type(ElementType.NobleGas)
        .Build();
    public static readonly Element Cs = new AtomBuilder()
        .Name("Cesium")
        .Symbol("Cs")
        .AtomicNumber(55)
        .AtomicMass(132.9054519)
        .OxidationStates(1)
        .Electronegativity(0.79)
        .IonizationEnergy(375.7)
        .ElectronAffinity(45.5)
        .AtomicRadius(260)
        .MeltingPoint(28.5)
        .BoilingPoint(671)
        .Type(ElementType.AlkaliMetal)
        .Build();

    public static readonly Element Ba = new AtomBuilder()
        .Name("Barium")
        .Symbol("Ba")
        .AtomicNumber(56)
        .AtomicMass(137.327)
        .OxidationStates(2)
        .Electronegativity(0.89)
        .IonizationEnergy(502.9)
        .ElectronAffinity(13.95)
        .AtomicRadius(215)
        .MeltingPoint(727)
        .BoilingPoint(1870)
        .Type(ElementType.AlkalineEarthMetal)
        .Build();

    public static readonly Element La = new AtomBuilder()
        .Name("Lanthanum")
        .Symbol("La")
        .AtomicNumber(57)
        .AtomicMass(138.90547)
        .OxidationStates(3)
        .Electronegativity(1.1)
        .IonizationEnergy(538.1)
        .ElectronAffinity(48)
        .AtomicRadius(195)
        .MeltingPoint(920)
        .BoilingPoint(3464)
        .Type(ElementType.Lanthanide)
        .Build();

    public static readonly Element Ce = new AtomBuilder()
        .Name("Cerium")
        .Symbol("Ce")
        .AtomicNumber(58)
        .AtomicMass(140.116)
        .OxidationStates(3, 4)
        .Electronegativity(1.12)
        .IonizationEnergy(534.4)
        .ElectronAffinity(50)
        .AtomicRadius(185)
        .MeltingPoint(798)
        .BoilingPoint(3426)
        .Type(ElementType.Lanthanide)
        .Build();

    public static readonly Element Pr = new AtomBuilder()
        .Name("Praseodymium")
        .Symbol("Pr")
        .AtomicNumber(59)
        .AtomicMass(140.90766)
        .OxidationStates(3, 4)
        .Electronegativity(1.13)
        .IonizationEnergy(527)
        .ElectronAffinity(50)
        .AtomicRadius(185)
        .MeltingPoint(931)
        .BoilingPoint(3520)
        .Type(ElementType.Lanthanide)
        .Build();

    public static readonly Element Nd = new AtomBuilder()
        .Name("Neodymium")
        .Symbol("Nd")
        .AtomicNumber(60)
        .AtomicMass(144.242)
        .OxidationStates(3)
        .Electronegativity(1.14)
        .IonizationEnergy(533.1)
        .ElectronAffinity(50)
        .AtomicRadius(185)
        .MeltingPoint(1021)
        .BoilingPoint(3100)
        .Type(ElementType.Lanthanide)
        .Build();

    public static readonly Element Pm = new AtomBuilder()
        .Name("Promethium")
        .Symbol("Pm")
        .AtomicNumber(61)
        .AtomicMass(145) // Note: Promethium is radioactive
        .OxidationStates(3)
        .Electronegativity(1.13)
        .IonizationEnergy(540)
        .ElectronAffinity(50)
        .AtomicRadius(183)
        .MeltingPoint(1042)
        .BoilingPoint(3000)
        .Type(ElementType.Lanthanide)
        .Build();

    public static readonly Element Sm = new AtomBuilder()
        .Name("Samarium")
        .Symbol("Sm")
        .AtomicNumber(62)
        .AtomicMass(150.36)
        .OxidationStates(2, 3)
        .Electronegativity(1.17)
        .IonizationEnergy(544.5)
        .ElectronAffinity(50)
        .AtomicRadius(180)
        .MeltingPoint(1072)
        .BoilingPoint(1900)
        .Type(ElementType.Lanthanide)
        .Build();

    public static readonly Element Eu = new AtomBuilder()
        .Name("Europium")
        .Symbol("Eu")
        .AtomicNumber(63)
        .AtomicMass(151.964)
        .OxidationStates(2, 3)
        .Electronegativity(1.2)
        .IonizationEnergy(547.1)
        .ElectronAffinity(50)
        .AtomicRadius(180)
        .MeltingPoint(822)
        .BoilingPoint(1597)
        .Type(ElementType.Lanthanide)
        .Build();
    public static readonly Element Gd = new AtomBuilder()
        .Name("Gadolinium")
        .Symbol("Gd")
        .AtomicNumber(64)
        .AtomicMass(157.25)
        .OxidationStates(3)
        .Electronegativity(1.2)
        .IonizationEnergy(593.4)
        .ElectronAffinity(50)
        .AtomicRadius(180)
        .MeltingPoint(1313)
        .BoilingPoint(3273)
        .Type(ElementType.Lanthanide)
        .Build();

    public static readonly Element Tb = new AtomBuilder()
        .Name("Terbium")
        .Symbol("Tb")
        .AtomicNumber(65)
        .AtomicMass(158.92535)
        .OxidationStates(3, 4)
        .Electronegativity(1.2)
        .IonizationEnergy(565.8)
        .ElectronAffinity(50)
        .AtomicRadius(177)
        .MeltingPoint(1356)
        .BoilingPoint(3230)
        .Type(ElementType.Lanthanide)
        .Build();

    public static readonly Element Dy = new AtomBuilder()
        .Name("Dysprosium")
        .Symbol("Dy")
        .AtomicNumber(66)
        .AtomicMass(162.500)
        .OxidationStates(3)
        .Electronegativity(1.22)
        .IonizationEnergy(573)
        .ElectronAffinity(50)
        .AtomicRadius(175)
        .MeltingPoint(1412)
        .BoilingPoint(2567)
        .Type(ElementType.Lanthanide)
        .Build();

    public static readonly Element Ho = new AtomBuilder()
        .Name("Holmium")
        .Symbol("Ho")
        .AtomicNumber(67)
        .AtomicMass(164.93033)
        .OxidationStates(3)
        .Electronegativity(1.23)
        .IonizationEnergy(581)
        .ElectronAffinity(50)
        .AtomicRadius(175)
        .MeltingPoint(1474)
        .BoilingPoint(2700)
        .Type(ElementType.Lanthanide)
        .Build();

    public static readonly Element Er = new AtomBuilder()
        .Name("Erbium")
        .Symbol("Er")
        .AtomicNumber(68)
        .AtomicMass(167.259)
        .OxidationStates(3)
        .Electronegativity(1.24)
        .IonizationEnergy(589.3)
        .ElectronAffinity(50)
        .AtomicRadius(175)
        .MeltingPoint(1529)
        .BoilingPoint(2868)
        .Type(ElementType.Lanthanide)
        .Build();

    public static readonly Element Tm = new AtomBuilder()
        .Name("Thulium")
        .Symbol("Tm")
        .AtomicNumber(69)
        .AtomicMass(168.93422)
        .OxidationStates(2, 3)
        .Electronegativity(1.25)
        .IonizationEnergy(596.7)
        .ElectronAffinity(50)
        .AtomicRadius(175)
        .MeltingPoint(1545)
        .BoilingPoint(1950)
        .Type(ElementType.Lanthanide)
        .Build();

    public static readonly Element Yb = new AtomBuilder()
        .Name("Ytterbium")
        .Symbol("Yb")
        .AtomicNumber(70)
        .AtomicMass(173.045)
        .OxidationStates(2, 3)
        .Electronegativity(1.1)
        .IonizationEnergy(603.4)
        .ElectronAffinity(50)
        .AtomicRadius(176)
        .MeltingPoint(824)
        .BoilingPoint(1196)
        .Type(ElementType.Lanthanide)
        .Build();

    public static readonly Element Lu = new AtomBuilder()
        .Name("Lutetium")
        .Symbol("Lu")
        .AtomicNumber(71)
        .AtomicMass(174.9668)
        .OxidationStates(3)
        .Electronegativity(1.27)
        .IonizationEnergy(523.5)
        .ElectronAffinity(50)
        .AtomicRadius(174)
        .MeltingPoint(1663)
        .BoilingPoint(3402)
        .Type(ElementType.Lanthanide)
        .Build();

    public static readonly Element Hf = new AtomBuilder()
        .Name("Hafnium")
        .Symbol("Hf")
        .AtomicNumber(72)
        .AtomicMass(178.49)
        .OxidationStates(4)
        .Electronegativity(1.3)
        .IonizationEnergy(658.5)
        .ElectronAffinity(0)
        .AtomicRadius(159)
        .MeltingPoint(2233)
        .BoilingPoint(4603)
        .Type(ElementType.TransitionMetal)
        .Build();

    public static readonly Element Ta = new AtomBuilder()
        .Name("Tantalum")
        .Symbol("Ta")
        .AtomicNumber(73)
        .AtomicMass(180.94788)
        .OxidationStates(5)
        .Electronegativity(1.5)
        .IonizationEnergy(761)
        .ElectronAffinity(31)
        .AtomicRadius(146)
        .MeltingPoint(3017)
        .BoilingPoint(5458)
        .Type(ElementType.TransitionMetal)
        .Build();

    public static readonly Element W = new AtomBuilder()
        .Name("Tungsten")
        .Symbol("W")
        .AtomicNumber(74)
        .AtomicMass(183.84)
        .OxidationStates(2, 3, 4, 5, 6)
        .Electronegativity(2.36)
        .IonizationEnergy(770)
        .ElectronAffinity(78.6)
        .AtomicRadius(139)
        .MeltingPoint(3422)
        .BoilingPoint(5930)
        .Type(ElementType.TransitionMetal)
        .Build();

    public static readonly Element Re = new AtomBuilder()
        .Name("Rhenium")
        .Symbol("Re")
        .AtomicNumber(75)
        .AtomicMass(186.207)
        .OxidationStates(-1, 1, 2, 3, 4, 5, 6, 7)
        .Electronegativity(1.9)
        .IonizationEnergy(760)
        .ElectronAffinity(5.827)
        .AtomicRadius(137)
        .MeltingPoint(3186)
        .BoilingPoint(5596)
        .Type(ElementType.TransitionMetal)
        .Build();

    public static readonly Element Os = new AtomBuilder()
        .Name("Osmium")
        .Symbol("Os")
        .AtomicNumber(76)
        .AtomicMass(190.23)
        .OxidationStates(-2, 2, 3, 4, 6, 8)
        .Electronegativity(2.2)
        .IonizationEnergy(840)
        .ElectronAffinity(103.99)
        .AtomicRadius(135)
        .MeltingPoint(3033)
        .BoilingPoint(5012)
        .Type(ElementType.TransitionMetal)
        .Build();

    public static readonly Element Ir = new AtomBuilder()
        .Name("Iridium")
        .Symbol("Ir")
        .AtomicNumber(77)
        .AtomicMass(192.217)
        .OxidationStates(-1, 1, 2, 3, 4, 6)
        .Electronegativity(2.2)
        .IonizationEnergy(880)
        .ElectronAffinity(150.94)
        .AtomicRadius(135)
        .MeltingPoint(2446)
        .BoilingPoint(4428)
        .Type(ElementType.TransitionMetal)
        .Build();

    public static readonly Element Pt = new AtomBuilder()
        .Name("Platinum")
        .Symbol("Pt")
        .AtomicNumber(78)
        .AtomicMass(195.084)
        .OxidationStates(2, 4, 6)
        .Electronegativity(2.28)
        .IonizationEnergy(870)
        .ElectronAffinity(205.041)
        .AtomicRadius(135)
        .MeltingPoint(1768.3)
        .BoilingPoint(3825)
        .Type(ElementType.TransitionMetal)
        .Build();

    public static readonly Element Au = new AtomBuilder()
        .Name("Gold")
        .Symbol("Au")
        .AtomicNumber(79)
        .AtomicMass(196.966569)
        .OxidationStates(1, 3)
        .Electronegativity(2.54)
        .IonizationEnergy(890.1)
        .ElectronAffinity(222.747)
        .AtomicRadius(135)
        .MeltingPoint(1064.18)
        .BoilingPoint(2856)
        .Type(ElementType.TransitionMetal)
        .Build();

    public static readonly Element Hg = new AtomBuilder()
        .Name("Mercury")
        .Symbol("Hg")
        .AtomicNumber(80)
        .AtomicMass(200.592)
        .OxidationStates(1, 2)
        .Electronegativity(2.00)
        .IonizationEnergy(1007.1)
        .ElectronAffinity(0)
        .AtomicRadius(150)
        .MeltingPoint(-38.83)
        .BoilingPoint(356.73)
        .Type(ElementType.TransitionMetal)
        .Build();

    public static readonly Element Tl = new AtomBuilder()
        .Name("Thallium")
        .Symbol("Tl")
        .AtomicNumber(81)
        .AtomicMass(204.38)
        .OxidationStates(1, 3)
        .Electronegativity(1.62)
        .IonizationEnergy(589.4)
        .ElectronAffinity(36.4)
        .AtomicRadius(190)
        .MeltingPoint(304)
        .BoilingPoint(1473)
        .Type(ElementType.PostTransitionMetal)
        .Build();

    public static readonly Element Pb = new AtomBuilder()
        .Name("Lead")
        .Symbol("Pb")
        .AtomicNumber(82)
        .AtomicMass(207.2)
        .OxidationStates(2, 4)
        .Electronegativity(2.33)
        .IonizationEnergy(715.6)
        .ElectronAffinity(34.4204)
        .AtomicRadius(175)
        .MeltingPoint(327.46)
        .BoilingPoint(1749)
        .Type(ElementType.PostTransitionMetal)
        .Build();

    public static readonly Element Bi = new AtomBuilder()
        .Name("Bismuth")
        .Symbol("Bi")
        .AtomicNumber(83)
        .AtomicMass(208.98040)
        .OxidationStates(3, 5)
        .Electronegativity(2.02)
        .IonizationEnergy(703)
        .ElectronAffinity(91.2)
        .AtomicRadius(160)
        .MeltingPoint(271.5)
        .BoilingPoint(1564)
        .Type(ElementType.PostTransitionMetal)
        .Build();

    public static readonly Element Po = new AtomBuilder()
        .Name("Polonium")
        .Symbol("Po")
        .AtomicNumber(84)
        .AtomicMass(209)
        .OxidationStates(2, 4)
        .Electronegativity(2.0)
        .IonizationEnergy(812.1)
        .ElectronAffinity(183.3)
        .AtomicRadius(190)
        .MeltingPoint(254)
        .BoilingPoint(962)
        .Type(ElementType.Metalloid)
        .Build();

    public static readonly Element At = new AtomBuilder()
        .Name("Astatine")
        .Symbol("At")
        .AtomicNumber(85)
        .AtomicMass(210)
        .OxidationStates(-1, 1, 3, 5)
        .Electronegativity(2.2)
        .IonizationEnergy(920)
        .ElectronAffinity(270.1)
        .AtomicRadius(202)
        .MeltingPoint(302)
        .BoilingPoint(337)
        .Type(ElementType.Metalloid)
        .Build();

    public static readonly Element Rn = new AtomBuilder()
        .Name("Radon")
        .Symbol("Rn")
        .AtomicNumber(86)
        .AtomicMass(222)
        .IonizationEnergy(1037)
        .AtomicRadius(220)
        .MeltingPoint(-71)
        .BoilingPoint(-61.7)
        .Type(ElementType.NobleGas)
        .Build();

    public static readonly Element Fr = new AtomBuilder()
        .Name("Francium")
        .Symbol("Fr")
        .AtomicNumber(87)
        .AtomicMass(223)
        .OxidationStates(1)
        .Electronegativity(0.7)
        .IonizationEnergy(380)
        .ElectronAffinity(46.89)
        .AtomicRadius(348)
        .MeltingPoint(27)
        .BoilingPoint(677)
        .Type(ElementType.AlkaliMetal)
        .Build();

    public static readonly Element Ra = new AtomBuilder()
        .Name("Radium")
        .Symbol("Ra")
        .AtomicNumber(88)
        .AtomicMass(226)
        .OxidationStates(2)
        .Electronegativity(0.9)
        .IonizationEnergy(509.3)
        .ElectronAffinity(0)
        .AtomicRadius(283)
        .MeltingPoint(700)
        .BoilingPoint(1737)
        .Type(ElementType.AlkalineEarthMetal)
        .Build();

    public static readonly Element Ac = new AtomBuilder()
        .Name("Actinium")
        .Symbol("Ac")
        .AtomicNumber(89)
        .AtomicMass(227)
        .OxidationStates(3)
        .Electronegativity(1.1)
        .IonizationEnergy(499)
        .ElectronAffinity(0)
        .AtomicRadius(260)
        .MeltingPoint(1050)
        .BoilingPoint(3200)
        .Type(ElementType.Actinide)
        .Build();

    public static readonly Element Th = new AtomBuilder()
        .Name("Thorium")
        .Symbol("Th")
        .AtomicNumber(90)
        .AtomicMass(232.03806)
        .OxidationStates(4)
        .Electronegativity(1.3)
        .IonizationEnergy(587)
        .ElectronAffinity(0)
        .AtomicRadius(237)
        .MeltingPoint(1750)
        .BoilingPoint(4788)
        .Type(ElementType.Actinide)
        .Build();

    public static readonly Element Pa = new AtomBuilder()
        .Name("Protactinium")
        .Symbol("Pa")
        .AtomicNumber(91)
        .AtomicMass(231.03588)
        .OxidationStates(4, 5)
        .Electronegativity(1.5)
        .IonizationEnergy(568)
        .ElectronAffinity(0)
        .AtomicRadius(243)
        .MeltingPoint(1568)
        .BoilingPoint(4027)
        .Type(ElementType.Actinide)
        .Build();
    public static readonly Element U = new AtomBuilder()
        .Name("Uranium")
        .Symbol("U")
        .AtomicNumber(92)
        .AtomicMass(238.02891)
        .OxidationStates(3, 4, 5, 6)
        .Electronegativity(1.38)
        .IonizationEnergy(597.6)
        .AtomicRadius(240)
        .MeltingPoint(1135)
        .BoilingPoint(4131)
        .Type(ElementType.Actinide)
        .Build();

    public static readonly Element Np = new AtomBuilder()
        .Name("Neptunium")
        .Symbol("Np")
        .AtomicNumber(93)
        .AtomicMass(237)
        .OxidationStates(3, 4, 5, 6, 7)
        .Electronegativity(1.36)
        .IonizationEnergy(604.5)
        .AtomicRadius(221)
        .MeltingPoint(644)
        .BoilingPoint(4000)
        .Type(ElementType.Actinide)
        .Build();

    public static readonly Element Pu = new AtomBuilder()
        .Name("Plutonium")
        .Symbol("Pu")
        .AtomicNumber(94)
        .AtomicMass(244)
        .OxidationStates(3, 4, 5, 6, 7, 8)
        .Electronegativity(1.28)
        .IonizationEnergy(584.7)
        .AtomicRadius(187)
        .MeltingPoint(639.4)
        .BoilingPoint(3228)
        .Type(ElementType.Actinide)
        .Build();

    public static readonly Element Am = new AtomBuilder()
        .Name("Americium")
        .Symbol("Am")
        .AtomicNumber(95)
        .AtomicMass(243)
        .OxidationStates(2, 3, 4, 5, 6)
        .Electronegativity(1.3)
        .IonizationEnergy(578)
        .AtomicRadius(180)
        .MeltingPoint(1176)
        .BoilingPoint(2607)
        .Type(ElementType.Actinide)
        .Build();

    public static readonly Element Cm = new AtomBuilder()
        .Name("Curium")
        .Symbol("Cm")
        .AtomicNumber(96)
        .AtomicMass(247)
        .OxidationStates(3, 4)
        .Electronegativity(1.3)
        .IonizationEnergy(581)
        .AtomicRadius(169)
        .MeltingPoint(1345)
        .BoilingPoint(3110)
        .Type(ElementType.Actinide)
        .Build();

    public static readonly Element Bk = new AtomBuilder()
        .Name("Berkelium")
        .Symbol("Bk")
        .AtomicNumber(97)
        .AtomicMass(247)
        .OxidationStates(3, 4)
        .Electronegativity(1.3)
        .IonizationEnergy(601)
        .AtomicRadius(168)
        .MeltingPoint(986)
        .BoilingPoint(2627)
        .Type(ElementType.Actinide)
        .Build();

    public static readonly Element Cf = new AtomBuilder()
        .Name("Californium")
        .Symbol("Cf")
        .AtomicNumber(98)
        .AtomicMass(251)
        .OxidationStates(2, 3, 4)
        .Electronegativity(1.3)
        .IonizationEnergy(608)
        .AtomicRadius(186)
        .MeltingPoint(900)
        .BoilingPoint(1470)
        .Type(ElementType.Actinide)
        .Build();

    public static readonly Element Es = new AtomBuilder()
        .Name("Einsteinium")
        .Symbol("Es")
        .AtomicNumber(99)
        .AtomicMass(252)
        .OxidationStates(2, 3)
        .Electronegativity(1.3)
        .IonizationEnergy(619)
        .AtomicRadius(186)
        .MeltingPoint(860)
        .BoilingPoint(996)
        .Type(ElementType.Actinide)
        .Build();

    public static readonly Element Fm = new AtomBuilder()
        .Name("Fermium")
        .Symbol("Fm")
        .AtomicNumber(100)
        .AtomicMass(257)
        .OxidationStates(2, 3)
        .Electronegativity(1.3)
        .IonizationEnergy(627)
        .AtomicRadius(186)  // Estimated
        .MeltingPoint(1527)  // Estimated
        .Type(ElementType.Actinide)
        .Build();

    public static readonly Element Md = new AtomBuilder()
        .Name("Mendelevium")
        .Symbol("Md")
        .AtomicNumber(101)
        .AtomicMass(258)
        .OxidationStates(2, 3)
        .Electronegativity(1.3)
        .IonizationEnergy(635)
        .AtomicRadius(186)  // Estimated
        .MeltingPoint(827)  // Estimated
        .Type(ElementType.Actinide)
        .Build();

    public static readonly Element No = new AtomBuilder()
        .Name("Nobelium")
        .Symbol("No")
        .AtomicNumber(102)
        .AtomicMass(259)
        .OxidationStates(2, 3)
        .Electronegativity(1.3)
        .IonizationEnergy(642)
        .AtomicRadius(185)  // Estimated
        .MeltingPoint(827)  // Estimated
        .Type(ElementType.Actinide)
        .Build();

    public static readonly Element Lr = new AtomBuilder()
        .Name("Lawrencium")
        .Symbol("Lr")
        .AtomicNumber(103)
        .AtomicMass(266)
        .OxidationStates(3)
        .Electronegativity(1.3)
        .IonizationEnergy(478)  // Estimated
        .AtomicRadius(180)  // Estimated
        .MeltingPoint(1627)  // Estimated
        .Type(ElementType.Actinide)
        .Build();

    public static readonly Element Rf = new AtomBuilder()
        .Name("Rutherfordium")
        .Symbol("Rf")
        .AtomicNumber(104)
        .AtomicMass(267)
        .OxidationStates(4)
        .Electronegativity(1.3)  // Estimated
        .IonizationEnergy(580)  // Estimated
        .AtomicRadius(150)  // Estimated
        .MeltingPoint(2100)  // Estimated
        .Type(ElementType.TransitionMetal)
        .Build();

    public static readonly Element Db = new AtomBuilder()
        .Name("Dubnium")
        .Symbol("Db")
        .AtomicNumber(105)
        .AtomicMass(268)
        .OxidationStates(5)
        .Electronegativity(1.3)  // Estimated
        .IonizationEnergy(664)  // Estimated
        .AtomicRadius(149)  // Estimated
        .MeltingPoint(1440)  // Estimated
        .Type(ElementType.TransitionMetal)
        .Build();

    public static readonly Element Sg = new AtomBuilder()
        .Name("Seaborgium")
        .Symbol("Sg")
        .AtomicNumber(106)
        .AtomicMass(269)
        .OxidationStates(6)
        .Electronegativity(1.3)  // Estimated
        .IonizationEnergy(740)  // Estimated
        .AtomicRadius(143)  // Estimated
        .MeltingPoint(1470)  // Estimated
        .Type(ElementType.TransitionMetal)
        .Build();

    public static readonly Element Bh = new AtomBuilder()
        .Name("Bohrium")
        .Symbol("Bh")
        .AtomicNumber(107)
        .AtomicMass(270)
        .OxidationStates(7)
        .Electronegativity(1.3)  // Estimated
        .IonizationEnergy(740)  // Estimated
        .AtomicRadius(141)  // Estimated
        .MeltingPoint(1500)  // Estimated
        .Type(ElementType.TransitionMetal)
        .Build();

    public static readonly Element Hs = new AtomBuilder()
        .Name("Hassium")
        .Symbol("Hs")
        .AtomicNumber(108)
        .AtomicMass(277)
        .OxidationStates(8)
        .Electronegativity(1.3)  // Estimated
        .IonizationEnergy(730)  // Estimated
        .AtomicRadius(134)  // Estimated
        .MeltingPoint(1500)  // Estimated
        .Type(ElementType.TransitionMetal)
        .Build();

    public static readonly Element Mt = new AtomBuilder()
        .Name("Meitnerium")
        .Symbol("Mt")
        .AtomicNumber(109)
        .AtomicMass(278)
        .OxidationStates(9)
        .Electronegativity(1.3)  // Estimated
        .IonizationEnergy(800)  // Estimated
        .AtomicRadius(130)  // Estimated
        .MeltingPoint(1100)  // Estimated
        .Type(ElementType.TransitionMetal)
        .Build();
    
        public static readonly Element Ds = new AtomBuilder()
        .Name("Darmstadtium")
        .Symbol("Ds")
        .AtomicNumber(110)
        .AtomicMass(281)
        .OxidationStates(8, 10)  // Estimated
        .Electronegativity(1.3)  // Estimated
        .IonizationEnergy(850)  // Estimated
        .AtomicRadius(128)  // Estimated
        .MeltingPoint(1100)  // Estimated
        .Type(ElementType.TransitionMetal)
        .Build();

    public static readonly Element Rg = new AtomBuilder()
        .Name("Roentgenium")
        .Symbol("Rg")
        .AtomicNumber(111)
        .AtomicMass(282)
        .OxidationStates(3, 5)  // Estimated
        .Electronegativity(1.3)  // Estimated
        .IonizationEnergy(920)  // Estimated
        .AtomicRadius(138)  // Estimated
        .MeltingPoint(1100)  // Estimated
        .Type(ElementType.TransitionMetal)
        .Build();

    public static readonly Element Cn = new AtomBuilder()
        .Name("Copernicium")
        .Symbol("Cn")
        .AtomicNumber(112)
        .AtomicMass(285)
        .OxidationStates(2, 4)  // Estimated
        .Electronegativity(1.3)  // Estimated
        .IonizationEnergy(1150)  // Estimated
        .AtomicRadius(147)  // Estimated
        .MeltingPoint(400)  // Estimated
        .BoilingPoint(357)  // Estimated
        .Type(ElementType.TransitionMetal)
        .Build();

    public static readonly Element Nh = new AtomBuilder()
        .Name("Nihonium")
        .Symbol("Nh")
        .AtomicNumber(113)
        .AtomicMass(286)
        .OxidationStates(1, 3)  // Estimated
        .Electronegativity(1.3)  // Estimated
        .IonizationEnergy(704)  // Estimated
        .AtomicRadius(170)  // Estimated
        .MeltingPoint(430)  // Estimated
        .Type(ElementType.PostTransitionMetal)
        .Build();

    public static readonly Element Fl = new AtomBuilder()
        .Name("Flerovium")
        .Symbol("Fl")
        .AtomicNumber(114)
        .AtomicMass(289)
        .OxidationStates(2, 4)  // Estimated
        .Electronegativity(1.3)  // Estimated
        .IonizationEnergy(823)  // Estimated
        .AtomicRadius(180)  // Estimated
        .MeltingPoint(340)  // Estimated
        .Type(ElementType.PostTransitionMetal)
        .Build();

    public static readonly Element Mc = new AtomBuilder()
        .Name("Moscovium")
        .Symbol("Mc")
        .AtomicNumber(115)
        .AtomicMass(290)
        .OxidationStates(1, 3)  // Estimated
        .Electronegativity(1.3)  // Estimated
        .IonizationEnergy(538)  // Estimated
        .AtomicRadius(187)  // Estimated
        .MeltingPoint(700)  // Estimated
        .Type(ElementType.PostTransitionMetal)
        .Build();

    public static readonly Element Lv = new AtomBuilder()
        .Name("Livermorium")
        .Symbol("Lv")
        .AtomicNumber(116)
        .AtomicMass(293)
        .OxidationStates(2, 4)  // Estimated
        .Electronegativity(1.3)  // Estimated
        .IonizationEnergy(723)  // Estimated
        .AtomicRadius(183)  // Estimated
        .MeltingPoint(700)  // Estimated
        .Type(ElementType.PostTransitionMetal)
        .Build();

    public static readonly Element Ts = new AtomBuilder()
        .Name("Tennessine")
        .Symbol("Ts")
        .AtomicNumber(117)
        .AtomicMass(294)
        .OxidationStates(1, 3, 5)  // Estimated
        .Electronegativity(1.3)  // Estimated
        .IonizationEnergy(742)  // Estimated
        .AtomicRadius(138)  // Estimated
        .MeltingPoint(610)  // Estimated
        .Type(ElementType.Halogen)
        .Build();

    public static readonly Element Og = new AtomBuilder()
        .Name("Oganesson")
        .Symbol("Og")
        .AtomicNumber(118)
        .AtomicMass(294)
        .OxidationStates(0)  // Estimated
        .Electronegativity(1.3)  // Estimated
        .IonizationEnergy(860)  // Estimated
        .AtomicRadius(152)  // Estimated
        .MeltingPoint(350)  // Estimated
        .Type(ElementType.NobleGas)
        .Build();
}